theme: jekyll-theme-cayman
title: Çağatay Nüfer Progress Journal
description: IE.48A Summer Term
# Assignment 1
To access the first assignment click [here](file:///C:/Users/w%C4%B1n/Desktop/Books/Assignment-1.html)
